services:
  mongo:
    image: mongo:7.0.21-jammy
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo_data:/data/db
  redis:
    image: redis:8.0.3-alpine
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  .mongo_data: